# Generated by Django 4.2.5 on 2023-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Дата последнего доступа')),
            ],
            options={
                'verbose_name': 'Аккаунты пользователей',
                'verbose_name_plural': 'Аккаунты пользователей',
                'ordering': ['created_time', 'fullname'],
            },
        ),
    ]
